let
    Origen = Json.Document(Web.Contents("http://127.0.0.1:8000/api/CumplidoMaquinaria/getAllCumplidosMaquinaria", [Headers=[Authorization="Bearer NdyNs18Z2D7eWHwr4wqcbSZqcGu6ekrvMwkNShHN1c4725ad"]])),
    #"Convertida en tabla" = Table.FromList(Origen, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Se expandió Column1" = Table.ExpandRecordColumn(#"Convertida en tabla", "Column1", {"fecha", "fecha_cierre","codigo", "Externo_Interno", "FincaExt", "LoteExt", "zona", "distrito", "finca", "finca_id", "lote", "lote_id", "cod_lote", "reg_lote_id", "hect_lote", "identificacion_operario", "operario", "operario_id", "maquina", "maquina_id", "horometro_ini", "horometro_fin", "horometro_total", "GalCombustible", "labor", "labor_id", "cant_trab", "valor_unit", "valor_total", "bultos_trab", "hect_trab", "horas_trab"}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Se expandió Column1",{{"fecha", type date},{"fecha_cierre", type date}, {"codigo", type text}, {"Externo_Interno", type text}, {"FincaExt", type text}, {"LoteExt", type text}, {"zona", type text}, {"distrito", type text}, {"finca", type text}, {"finca_id", Int64.Type}, {"lote", type text}, {"lote_id", Int64.Type}, {"cod_lote", type text}, {"reg_lote_id", Int64.Type}, {"hect_lote", Int64.Type}, {"identificacion_operario", Int64.Type}, {"operario", type text}, {"operario_id", Int64.Type}, {"maquina", type text}, {"maquina_id", Int64.Type}, {"horometro_ini", Int64.Type}, {"horometro_fin", Int64.Type}, {"horometro_total", Int64.Type}, {"GalCombustible", Int64.Type}, {"labor", type text}, {"labor_id", Int64.Type}, {"cant_trab", type number}, {"valor_unit", Int64.Type}, {"valor_total", Int64.Type}, {"bultos_trab", Int64.Type}, {"hect_trab", type number}, {"horas_trab", Int64.Type}})
in
    #"Tipo cambiado"